####Resumen artículo  

##High-throughput transcriptome sequencing and comparative analysis of *Escherichia coli* and *Schizosaccharomyces pombe* in respiratory and fermentative growth 

El presente artículo de investigación se centra en el análisis transcripcional comparativo de dos organismos modelo pertenecientes a dominios distintos de la vida, *Escherichia coli*, una bacteria Gram negativa, y *Schizosaccharomyces pombe*, una levadura de fisión; ambos organismos, a pesar de su lejanía evolutiva, comparten procesos metabólicos básicos, lo que los convierte en sistemas de referencia útiles para la exploración de similitudes y diferencias en la respuesta a distintas condiciones de crecimiento.  

Los investigadores se centraron en la comparación génica en dos condiciones metabólicas distintas: la primera en presencia de glucosa (al 2%), la cual favorece la fermentación, y la segunda, una mezcla de glicerol y acetato de sodio (2% y 0.2%, respectivamente), que promueve la respiración. Para reducir variaciones experimentales, ambos organismos se cultivaron en el mismo medio base y en fases equivalentes de crecimiento. El objetivo fue identificar genes ortólogos y rutas conservadas, así como adaptaciones específicas a cada dominio de la vida, poniendo énfasis en la participación de ncRNAs en la regulación.  

Para ello, se extrajo el ARN total, se construyeron bibliotecas y se realizó secuenciación masiva mediante tecnología Illumina. Los datos fueron analizados con herramientas bioinformáticas que permitieron detectar genes diferencialmente expresados y evaluar rutas metabólicas conservadas y específicas de cada organismo.  

Para los dos organismos, se generaron 10 millones de lecturas de secuenciación y se analizaron alrededor de 100 genes que codifican para proteínas; los resultados generales de los análisis transcripcionales permitieron identificar 593 genes diferencialmente expresados en *E. coli* y 860 en *S. pombe*. Los datos de expresión génica generados en este trabajo se depositaron en la base de datos NCBI GEO bajo el **BioProject ID: GSE138088**.  

En el análisis comparativo, se identificaron 718 ortólogos y 262 co-ortólogos entre *E. coli* y *S. pombe*, formando 343 grupos conservados asociados en su mayoría a la glucólisis y al ciclo del ácido tricarboxílico. Estos resultados destacan la conservación evolutiva en el metabolismo central; de igual manera, los resultados demostraron funciones específicas de cada linaje: en el caso de *S. pombe*, se destacó la traducción, transcripción y biogénesis de ribosomas, mientras que en *E. coli* predominaron funciones de membrana, transporte de azúcares y captación de aminoácidos.  

El análisis transcripcional mostró claras diferencias entre ambas condiciones; en glucosa, ambos organismos expresaron genes asociados a la proliferación, mientras que en glicerol/acetato *E. coli* sobreexpresó genes para el transporte de glicerol y el ensamblaje flagelar, y *S. pombe* activó transportadores de hexosas y hierro, junto con más de 300 ARN largos no codificantes (ncRNAs).  

El análisis de enriquecimiento funcional confirmó que la glucosa favorece rutas orientadas al crecimiento, como el metabolismo de aminoácidos, la glucólisis y la fosforilación oxidativa, mientras que en glicerol/acetato las respuestas convergieron en procesos de metabolismo y regulación de ncRNAs, con adaptaciones específicas en cada especie, como genes de motilidad en *E. coli* y genes meióticos o de transporte de iones en *S. pombe*.  

Los análisis fenotípicos realizados respaldaron estos cambios; en la condición de glicerol/acetato, *E. coli* desarrolló flagelos visibles, mientras que las células de *S. pombe* se volvieron más pequeñas y redondeadas, contrastando con la morfología alargada que se observa en glucosa. Ambos organismos también activaron genes del metabolismo de galactosa y transportadores de hexosas de alta afinidad, reflejando un ajuste metabólico conservado. En conjunto, estos hallazgos sugieren que el crecimiento respiratorio induce un estado similar a un **“foraging behavior”**, donde las células invierten en la captura de nutrientes, la tolerancia al estrés y el uso de rutas metabólicas alternativas, con los ncRNAs desempeñando un papel especialmente central en *S. pombe*.  

En conclusión, el estudio determina que la glucosa apoya de manera consistente el crecimiento y la proliferación celular tanto en procariotas como en eucariotas, mientras que el glicerol/acetato activa programas adaptativos semejantes al **“foraging behavior”**, que incluyen motilidad, adaptación al estrés y flexibilidad metabólica. A pesar de sus diferencias, tanto *E. coli* como *S. pombe* dependen de estrategias transcripcionales conservadas, lo que enfatiza la importancia evolutiva de los ncRNAs y de las vías de señalización en la configuración de las estrategias de supervivencia.  
